Repository netsampler/goflow2, pull requests merged in 2021-06, with the labels that each got.

#5 Add new compose stack
  README.md
  compose/elk/README.md
  compose/elk/docker-compose.yml
  compose/elk/logstash.conf
  compose/grafana/dashboards/viz.json
  compose/grafana/datasources.yml
  compose/kcg/README.md
  compose/kcg/clickhouse/create.sh
  compose/kcg/clickhouse/protocols.csv
  compose/kcg/docker-compose.yml
  compose/kcg/grafana/Dockerfile
  compose/kcg/grafana/dashboards.yml
  compose/kcg/grafana/dashboards/perfs.json
  compose/kcg/grafana/dashboards/viz-ch.json
  compose/kcg/grafana/datasources-ch.yml
  compose/kcg/prometheus/prometheus.yml
Labels: compose, documentation, enhancement

#4 feature: implement SIGHUP for log rotation
  transport/file/transport.go
Labels: enhancement

#7 Fix few typos in readme
  README.md
Labels: documentation

#9 Fix protobuf
  Makefile
  README.md
  cmd/enricher/pb/flowext.pb.go
  cmd/enricher/pb/flowext.proto
  docs/protobuf.md
  pb/flow.pb.go
  pb/flow.proto
Labels: documentation, proto

#10 Ensure line feed in Makefile
  Makefile
Labels: build

#16 Bugfix NetFlow/IPFIX producer
  producer/producer_nf.go
  utils/sflow_test.go
Labels: bug, ipfix
