Repository netsampler/goflow2, pull requests merged in 2021-09, with the labels that each got.

#36 Custom map flow fields
  cmd/goflow2/main.go
  cmd/goflow2/mapping.yaml
  decoders/netflow/netflow.go
  decoders/netflow/packet.go
  docs/protocols.md
  format/common/text.go
  go.mod
  go.sum
  pb/flow.pb.go
  pb/flow.proto
  producer/producer_nf.go
  producer/producer_sf.go
  producer/reflect.go
  utils/netflow.go
  utils/sflow.go
  utils/utils.go
Labels: enhancement, ipfix, proto, format, sflow

#38 style: defer unlock when possible/not trivial
  decoders/netflow/netflow.go
  format/format.go
  producer/producer_nf.go
  transport/transport.go
Labels: enhancement

#39 netflow: correctly decode options template set
  decoders/netflow/netflow.go
  decoders/netflowlegacy/netflow.go
  decoders/sflow/sflow.go
Labels: bug, ipfix
