Repository netsampler/goflow2, pull requests merged in 2023-08, with the labels that each got.

#197 goflow2: allows using a single port for multiple protocols (sFlow, NetFlow, IPFIX)
  cmd/goflow2/main.go
  utils/pipe.go
Labels: enhancement

#141 decoders: replace binary.Read with a version without reflection and allocations
  decoders/netflow/netflow.go
  decoders/netflowlegacy/netflow.go
  decoders/sflow/sflow.go
  decoders/utils/utils.go
  decoders/utils/utils_test.go
  producer/producer_nf.go
Labels: ipfix, sflow

#209 fix: missing time received ns in netflow v5
  producer/proto/proto.go
Labels: nfv5
