Repository netsampler/goflow2, pull requests merged in 2024-03, with the labels that each got.

#293 docs: fix typo in readme.md
  README.md
Labels: documentation

#299 bug: fix builds to push latest tag
  .github/workflows/docker-release.yml
  .github/workflows/docker-release_registry_github.yml
  .github/workflows/docker.yml
  .github/workflows/docker_registry_github.yml
Labels: bug, compose, build

#300 bug: fix builds to push latest tag
  .github/workflows/docker-release.yml
  .github/workflows/docker-release_registry_github.yml
  .github/workflows/docker.yml
  .github/workflows/docker_registry_github.yml
Labels: bug, build

#301 bug: fix builds to push latest tag
  .github/workflows/docker-release.yml
  .github/workflows/docker-release_registry_github.yml
  .github/workflows/docker.yml
  .github/workflows/docker_registry_github.yml
Labels: bug, build

#302 bug: fix double count of NetFlow metric
  metrics/decoder.go
Labels: bug
