Repository netsampler/goflow2, pull requests merged in 2024-01, with the labels that each got.

#272 docs: add softflowd
  docs/agents.md
Labels: documentation

#226 metrics: collect drops on receiver
  cmd/goflow2/main.go
  metrics/metrics.go
  metrics/receiver.go
  utils/udp.go
Labels: enhancement, performance

#261 decoders: fix sflow parsing of IP and MAC addresses
  decoders/sflow/datastructure.go
  decoders/sflow/packet.go
  decoders/utils/types.go
  decoders/utils/utils.go
Labels: bug, sflow

#249 transport: mute errors when too verbose
  cmd/goflow2/main.go
  utils/mute.go
  utils/mute_test.go
Labels: enhancement, transport

#277 feat: add string renderer
  producer/proto/messages.go
  producer/proto/messages_test.go
  producer/proto/render.go
Labels: test, producer
